name: "bluebell"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2022-05-01"
machine-id: 1
log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root1234"
  dbname: "bluebell"
  max_open_conns: 20
  max_idle_conns: 10
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100